### ISSUE TITLE
Elaborate needs for API calls with more extensive UML

### ISSUE THREAD

**Issue by jonasschjerlund** [jonasschjerlund/SOVA#10]
We need to map our actual needs more. What kind of data do we actually need to return for the various API calls? Use system sequence and use case diagrams to illustrate thought process.

@MadsSK

**Comment by Chronim** [comment]
Made 4 SSQ diagrams for "Mark Favorite"; "Search By String", "Search By Post" and "Search By Tag".
Also expanded the Use Case Diagram, to include the different ways of searching.

**Comment by Chronim** [comment]
Ahem 4...
