### ISSUE TITLE
Create preliminary API documentation

### ISSUE THREAD

**Issue by jonasschjerlund** [jonasschjerlund/SOVA#11]
This is a multi-faceted task, as it also allows us to familiarize ourselves with the github wiki. We have a decent starting point now, with an API list with a list of data structures needed for the API calls listed [here](https://github.com/ruc-RAWDATA-striketeam/SOVA/wiki/HTTP-web-service-API-Overview). Elaborate and expand on these, try to describe the rationale behind their design and what they must contain. Connected to #10 .

@ruc-RAWDATA-striketeam/everybody

**Comment by ghost** [comment]
Has created a preliminary API, but it will be constantly modified.

"It always seems impossible until its done." - Nelson Mandela
