### ISSUE TITLE
Restructure code and experiment with superclass abstraction for questions and answers

### ISSUE THREAD

**Issue by jonasschjerlund** [jonasschjerlund/SOVA#21]
A matter of playing around with the layers and class structure. Since questions and answers share some attributes, it might be beneficial for longterm maintenance to introduce an abstract class that holds the identical attributes, for the respective question and answer classes to inherit from.

**Comment by Chronim** [comment]
Post has been turned into an abstract class and classes Answer and Question now implement Post.
Changes have been made to Domain layer and DAL to work with this new Super- Subclass model.
