### ISSUE TITLE
Git integration

### ISSUE THREAD

**Issue by jonasschjerlund** [jonasschjerlund/SOVA#9]
We need to get git integration fully operational on everybody's PCs. The easiest way to clone a repository is through the command console. Navigate to the folder where you want the project to be, and run the following command:

`git clone https://github.com/ruc-RAWDATA-striketeam/SOVA.git SOVA`

This will create a project that you can then open in Visual Studio. It will automatically restore NuGet dependencies on first launch.

Please comment here when everything works, then we can close this issue.

@ruc-RAWDATA-striketeam/everybody

**Comment by Chronim** [comment]
I have achieved the full git integration by following this well made description, and I therefore move to close this issue.

Best Greetings
Nedim Zahirovic

**Comment by jonasschjerlund** [comment]
Everything works for me. Make sure to change the remote origin URL if you're still on the old repository address (the one under my github account).

**Comment by ghost** [comment]
Done. 

Tested with a commit and a push from local repository to GitHub branch "MadsTest"

"Great things are done by a series of small things brought together." - Vincent Van Gogh
